name: .NET CI Workflow

# Define quando o workflow será acionado
on:
  push:
    branches:
      - main   # Ou o nome da branch principal do seu repositório
  pull_request:
    branches:
      - main   # Aciona o workflow também quando um PR é feito para a branch principal
  workflow_dispatch:  # Permite a execução manual do workflow

# Define os jobs do workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Define o sistema operacional para rodar os testes

    steps:
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do .NET SDK (especificando a versão 8.0)
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restaurar as dependências do projeto
      - name: Restore dependencies
        run: dotnet restore

      # Build do projeto
      - name: Build
        run: dotnet build --configuration Release

      # Rodar os testes e gerar relatório no formato JUnit
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "junit;LogFileName=test-results.xml"

      # Fazer upload do relatório de testes (versão mais específica)
      - name: Upload test results
        uses: actions/upload-artifact@v2.3.0  # Tente usar v2.3.0 para garantir compatibilidade
        with:
          name: test-results
          path: test-results.xml
